// Research pass — own-corpus + trends summarizer.
//
// Input: a topic string and optional pillar_id. Output: a 2-3 sentence
// summary + a deterministic citation list. Voice-AGNOSTIC. No web
// scraping or external HTTP egress -- the rule for vNext is "all signal
// from data we already have." Sources:
//
//   1. The user's own transcripts (via match_transcripts_by_essence RPC,
//      which embeds the topic and finds top-N transcripts by cosine).
//   2. Recent tiktok_trends rows for the pillar's industry_id (if set).
//   3. Recent reddit_trends rows for the pillar's subreddits (if set).
//
// One Groq call summarizes; one HF call embeds the topic for the
// transcript match. Citations are NOT generated by the LLM -- they're
// the deterministic rows that fed the summary, so the UI can link back
// to original transcripts/trends.

import Groq from 'groq-sdk';
import { requireEnv } from '@/lib/env';
import { embedText } from '@/lib/pillars/embeddings';
import type { SupabaseServer } from '@/lib/pillars/types';

const MODEL = 'llama-3.3-70b-versatile';
const TEMPERATURE = 0.3;
const TRANSCRIPT_LIMIT = 5;
const TRANSCRIPT_THRESHOLD = 0.45;
const TIKTOK_LIMIT = 5;
const REDDIT_LIMIT = 5;
const TRANSCRIPT_SNIPPET_CHARS = 280;
const SUMMARY_OUTPUT_CAP = 800;

export type ResearchCitation =
    | { source: 'transcript';    ref_id: string; snippet: string; similarity?: number }
    | { source: 'tiktok_trend';  ref_id: string; snippet: string }
    | { source: 'reddit_trend';  ref_id: string; snippet: string };

export interface ResearchResult {
    summary: string;
    citations: ResearchCitation[];
    groqCalls: number;
    hfCalls: number;
}

export interface RunResearchArgs {
    supabase: SupabaseServer;
    userId: string;
    topic: string;
    pillarId?: string | null;
}

export const RESEARCH_SYSTEM_MESSAGE = `You write tight 2-3 sentence research notes for a creator who's about to brainstorm video concepts. You DO NOT mimic any creator voice. Use only the provided context (the creator's own past transcripts and current trend signals). If the context is thin, say so plainly rather than inventing.

Output STRICT JSON:

{ "summary": "<2-3 sentences. Salient observations and what's underexplored.>" }

DO NOT invent statistics, hashtags, or quotes that aren't in the context. DO NOT cite imaginary studies. If trends data is empty for a niche, do not pretend otherwise.`;

export async function runResearch(args: RunResearchArgs): Promise<ResearchResult> {
    const { supabase, userId, topic, pillarId } = args;
    const cleanTopic = topic.trim();
    if (!cleanTopic) throw new Error('research: topic is required');

    let groqCalls = 0;
    let hfCalls = 0;

    // 1. Pillar context (if provided) — needed to filter trends rows.
    interface PillarRow {
        id: string;
        name: string;
        tiktok_industry_id: string | null;
        reddit_subreddits: string[] | null;
    }
    let pillarRow: PillarRow | null = null;
    if (pillarId) {
        const { data } = await supabase
            .from('pillars')
            .select('id, name, tiktok_industry_id, reddit_subreddits')
            .eq('user_id', userId)
            .eq('id', pillarId)
            .single();
        if (data) {
            pillarRow = data as PillarRow;
        }
    }

    // 2. Embed the topic for transcript matching. If HF cold-starts, fall
    //    back to skipping the transcript pull (we still have trends).
    let topicEmbedding: number[] | null = null;
    try {
        topicEmbedding = await embedText(cleanTopic);
        hfCalls++;
    } catch (err) {
        console.warn('research: HF embed failed, skipping transcript match:', err);
    }

    // 3. Transcript matches via existing RPC (essence-level cosine). The
    //    RPC filters by user_id server-side.
    const transcriptRows: Array<{ transcript_id: string; similarity: number; essence: string }> = [];
    if (topicEmbedding) {
        const { data, error } = await supabase.rpc('match_transcripts_by_essence', {
            p_user_id: userId,
            p_embedding: topicEmbedding,
            p_exclude_pillar_id: null,
            p_limit: TRANSCRIPT_LIMIT,
        });
        if (!error && Array.isArray(data)) {
            for (const r of data as Array<{ transcript_id: string; similarity: number; essence: string }>) {
                if (r.similarity >= TRANSCRIPT_THRESHOLD) transcriptRows.push(r);
            }
        }
    }

    // 4. tiktok_trends — recent rows for the pillar's industry.
    type TikTokRow = { id: string; hashtag_id: string; hashtag_name: string; rank: number | null; rank_diff: number | null };
    let tiktokRows: TikTokRow[] = [];
    if (pillarRow?.tiktok_industry_id) {
        const { data } = await supabase
            .from('tiktok_trends')
            .select('id, hashtag_id, hashtag_name, rank, rank_diff')
            .eq('industry_id', pillarRow.tiktok_industry_id)
            .order('fetched_at', { ascending: false })
            .limit(TIKTOK_LIMIT);
        if (data) tiktokRows = data as TikTokRow[];
    }

    // 5. reddit_trends — recent rows for the pillar's subreddits.
    type RedditRow = { id: string; post_id: string; subreddit: string; title: string; score: number | null; num_comments: number | null };
    let redditRows: RedditRow[] = [];
    if (pillarRow?.reddit_subreddits && pillarRow.reddit_subreddits.length > 0) {
        const { data } = await supabase
            .from('reddit_trends')
            .select('id, post_id, subreddit, title, score, num_comments')
            .in('subreddit', pillarRow.reddit_subreddits)
            .order('fetched_at', { ascending: false })
            .limit(REDDIT_LIMIT);
        if (data) redditRows = data as RedditRow[];
    }

    // 6. Build the prompt context.
    const contextBlocks: string[] = [];
    contextBlocks.push(`TOPIC: ${cleanTopic}`);
    if (pillarRow) {
        contextBlocks.push(`PILLAR: ${pillarRow.name}`);
    }

    if (transcriptRows.length > 0) {
        contextBlocks.push('');
        contextBlocks.push("CREATOR'S OWN PAST TRANSCRIPTS (snippets, ranked by topical similarity):");
        transcriptRows.forEach((t, i) => {
            const snippet = (t.essence ?? '').slice(0, TRANSCRIPT_SNIPPET_CHARS);
            contextBlocks.push(`  T${i + 1} [sim=${t.similarity.toFixed(2)}]: ${snippet}`);
        });
    }

    if (tiktokRows.length > 0) {
        contextBlocks.push('');
        contextBlocks.push('TIKTOK TRENDS (current, this pillar\'s industry):');
        tiktokRows.forEach((r, i) => {
            const move = r.rank_diff ? ` (rank Δ ${r.rank_diff})` : '';
            contextBlocks.push(`  TT${i + 1}: #${r.hashtag_name} rank ${r.rank ?? '?'}${move}`);
        });
    }

    if (redditRows.length > 0) {
        contextBlocks.push('');
        contextBlocks.push("REDDIT TRENDS (current, this pillar's subreddits):");
        redditRows.forEach((r, i) => {
            contextBlocks.push(`  R${i + 1}: r/${r.subreddit} · ${r.title} (${r.score ?? 0} pts, ${r.num_comments ?? 0} comments)`);
        });
    }

    const hasAnyContext = transcriptRows.length + tiktokRows.length + redditRows.length > 0;
    if (!hasAnyContext) {
        contextBlocks.push('');
        contextBlocks.push('(no own-corpus or trend signal available for this topic)');
    }

    // 7. Groq summarize.
    const groq = new Groq({ apiKey: requireEnv('GROQ_API_KEY') });
    const completion = await groq.chat.completions.create({
        model: MODEL,
        messages: [
            { role: 'system', content: RESEARCH_SYSTEM_MESSAGE },
            { role: 'user',   content: contextBlocks.join('\n') },
        ],
        temperature: TEMPERATURE,
        response_format: { type: 'json_object' },
    });
    groqCalls++;

    const content = stripFences(completion.choices[0]?.message?.content ?? '{}');
    let parsed: unknown;
    try {
        parsed = JSON.parse(content);
    } catch (err) {
        throw new Error(`research: unparseable JSON: ${(err as Error).message}`);
    }

    const summary = (
        parsed && typeof parsed === 'object' && !Array.isArray(parsed)
            ? String((parsed as Record<string, unknown>).summary ?? '')
            : ''
    ).trim().slice(0, SUMMARY_OUTPUT_CAP);

    if (!summary) throw new Error('research: empty summary returned');

    // 8. Build deterministic citations from the rows we pulled. The LLM
    //    doesn't get to invent IDs — these are exactly what fed the
    //    summary, in the same order the prompt presented them.
    const citations: ResearchCitation[] = [
        ...transcriptRows.map((t): ResearchCitation => ({
            source: 'transcript',
            ref_id: t.transcript_id,
            snippet: (t.essence ?? '').slice(0, TRANSCRIPT_SNIPPET_CHARS),
            similarity: Number(t.similarity.toFixed(3)),
        })),
        ...tiktokRows.map((r): ResearchCitation => ({
            source: 'tiktok_trend',
            ref_id: r.hashtag_id,
            snippet: `#${r.hashtag_name} rank ${r.rank ?? '?'}${r.rank_diff ? ` (Δ ${r.rank_diff})` : ''}`,
        })),
        ...redditRows.map((r): ResearchCitation => ({
            source: 'reddit_trend',
            ref_id: r.post_id,
            snippet: `r/${r.subreddit} · ${r.title}`,
        })),
    ];

    return { summary, citations, groqCalls, hfCalls };
}

// ---- helpers --------------------------------------------------------------

function stripFences(s: string): string {
    let out = s.trim();
    if (out.startsWith('```json')) out = out.replace(/^```json\s*/i, '').replace(/```$/i, '').trim();
    else if (out.startsWith('```')) out = out.replace(/^```\s*/, '').replace(/```$/, '').trim();
    return out;
}
